# Establecer la imagen base
FROM node:20

# Crear y establecer el directorio de trabajo
RUN mkdir /project
WORKDIR /project

RUN npm install -g @angular/cli 

# Copiar los archivos de la aplicación
COPY package.json package-lock.json ./
RUN npm ci


# Copiar el resto de la aplicación
COPY . .

# Compilar la aplicación
CMD ["ng",  "serve", "--host", "0.0.0.0"]